name: taxi_rides_hourly_features_pipeline

on:
  schedule:
    - cron: '2 * * * *'  # Runs every hour
  workflow_dispatch:      # Allows manual triggering of the workflow

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Specify the Python version

      - name: Install latest librdkafka from Confluent repository
        run: |
          sudo apt-get update
          sudo apt-get install -y wget software-properties-common
          wget -qO - https://packages.confluent.io/deb/7.4/archive.key | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/7.4 stable main"
          sudo apt-get update && sudo apt-get install -y librdkafka-dev

      - name: Install dependencies with confluent-kafka from Confluent index
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          # Install confluent-kafka from Confluent's extra index to get precompiled wheels
          pip install confluent-kafka --extra-index-url https://packages.confluent.io/pypi/simple
          pip install -r requirements_feature_pipeline.txt

      - name: Run new data fetch pipeline and load to hopsworks
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: python -m src.feature_pipeline
